---
Description: ""
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TransferFamilyRoleArn:
    Type: String
    Description: "Transfer family service role arn (Optional)"
  UsersRoleArn:
    Type: String
    Description: "Transfer family users role arn (Optional)"
  BucketNameOfHome:
    Type: String
    Description: "SFTP Server default home directory"
Conditions:
  CreateServiceRole: !Equals
    - !Ref TransferFamilyRoleArn
    - ""
  CreateUsersRole: !Equals
    - !Ref UsersRoleArn
    - ""
Resources:
  BucketOfHomeA4DCBFA9:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Ref BucketNameOfHome
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  AWSTransferLoggingAccess:
    Type: AWS::IAM::Role
    Condition: CreateServiceRole
    Properties:
      RoleName: AWSTransferLoggingAccess
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
        Version: "2012-10-17"
      Path: "/"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSTransferLoggingAccess'
  AWSTransferUsersAccess:
    Type: AWS::IAM::Role
    Condition: CreateUsersRole
    Properties:
      RoleName: AWSTransferUsersAccess
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyName: TransferFamilyUsers
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: s3:ListBucket
                Resource: !Join ['', ['arn:aws:s3:::', !Ref 'BucketOfHomeA4DCBFA9']]
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                  - "s3:DeleteObjectVersion"
                  - "s3:GetObjectVersion"
                  - "s3:GetObjectACL"
                  - "s3:PutObjectACL"
                Resource: !Join ['', ['arn:aws:s3:::', !Ref 'BucketOfHomeA4DCBFA9', /*]]
  TransferFamilyServer:
    Type: AWS::Transfer::Server
    Properties:
      IdentityProviderType: SERVICE_MANAGED
      LoggingRole: !If [CreateServiceRole, !GetAtt AWSTransferLoggingAccess.Arn, !Ref TransferFamilyRoleArn]
      Protocols:
        - SFTP
Outputs:
  TransferFamilyServerId:
    Description: "Transfer family server id"
    Value: !GetAtt TransferFamilyServer.ServerId
    Export:
      Name: !Sub '${AWS::StackName}-TransferFamilyServerId'
